behaviors:
    Park:
        # Trainer configurations
        trainer_type: ppo
        summary_freq: 50000
        max_steps: 100000000
        time_horizon: 1024
        threaded: True
        keep_checkpoints: 20
        checkpoint_interval: 5000000

        # Hyperparameters
        hyperparameters:
            batch_size: 512
            buffer_size: 10240
            learning_rate: 1.0e-3
            learning_rate_schedule: linear

            # PPO specific
            beta: 1.0e-3
            epsilon: 0.2
            lambd: 0.95
            num_epoch: 3

        # Neural network settings
        network_settings:
            normalize: True
            hidden_units: 256
            num_layers: 3
            vis_encode_type: simple

        reward_signals:
            extrinsic:
                strength: 1.0
                gamma: 0.99
            gail:
                strength: 0.3
                gamma: 0.99
                demo_path: path to the demo file
